apiVersion: v1
kind: Pod
metadata:
  name: service-demo
# these labels are used to register this pod with service - ( spec.selector.items )
  labels:
    project: roboshop
    component: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx