apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  # this are replica set labels
  labels:
    purpose: rs-demo
    project: roboshop
spec:
  replicas: 5
  selector:
  # these labels are used to select pods
    matchLabels:
      purpose: rs-demo
      project: roboshop
  template:
    metadata:
    # these labels are pod definition 
      labels:
        purpose: rs-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx